/home/maellef/Friends_train/lib/python3.6/site-packages/nilearn/datasets/__init__.py:90: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  "Numpy arrays.", FutureWarning)
Parcellating file /home/maellef/projects/rrg-pbellec/datasets/cneuromod_new/friends/derivatives/fmriprep-20.1.0/fmriprep/sub-04/ses-001/func/sub-04_ses-001_task-s01e01b_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
saving ROI parcellations ...
/home/maellef/DataBase/fMRI_Embeddings/Friends/embed_2021_norm/sub-04/auditory_Voxels/sub-04_ses-001_task-s01e01b
saving voxel parcellations ...
Parcellating file /home/maellef/projects/rrg-pbellec/datasets/cneuromod_new/friends/derivatives/fmriprep-20.1.0/fmriprep/sub-04/ses-001/func/sub-04_ses-001_task-s01e01a_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
saving ROI parcellations ...
/home/maellef/DataBase/fMRI_Embeddings/Friends/embed_2021_norm/sub-04/auditory_Voxels/sub-04_ses-001_task-s01e01a
saving voxel parcellations ...
Parcellating file /home/maellef/projects/rrg-pbellec/datasets/cneuromod_new/friends/derivatives/fmriprep-20.1.0/fmriprep/sub-04/ses-012/func/sub-04_ses-012_task-s02e02a_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
Traceback (most recent call last):
  File "../parcellation/parcellation_utils.py", line 108, in <module>
    parcellate_MIST(filepath,save=True,savepath=savepath)
  File "../parcellation/parcellation_utils.py", line 80, in parcellate_MIST
    confounds = Params24().load(tsvfile_fmri)
  File "/home/maellef/Friends_train/lib/python3.6/site-packages/load_confounds/parser.py", line 325, in load
    conf, col = self._load_single(file)
  File "/home/maellef/Friends_train/lib/python3.6/site-packages/load_confounds/parser.py", line 351, in _load_single
    confounds_high_pass = _load_high_pass(confounds_raw)
  File "/home/maellef/Friends_train/lib/python3.6/site-packages/load_confounds/parser.py", line 76, in _load_high_pass
    high_pass_params = _find_confounds(confounds_raw, ["cosine"])
  File "/home/maellef/Friends_train/lib/python3.6/site-packages/load_confounds/parser.py", line 56, in _find_confounds
    raise ValueError(f"could not find any confound with the key {key}")
ValueError: could not find any confound with the key cosine
